### ISSUE TITLE
Make "batch" function payable

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#1090]
https://github.com/sablier-labs/company-discussions/discussions/72#discussioncomment-11292236

- [x] Mark all functions as `payable`.
- [x] Do **NOT** emit the fee in any event because the withdraw function can be called in multiple ways, e.g, directly via `withdraw`, via `withdrawMultiple`, or via `batch`, which would make the accounting difficult to handle.

We will keep track of ETH transfers through other means, e.g., Etherscan, subgraphs, etc.

**Comment by smol-ninja** [comment]
Lets include this change alongside making other withdraw functions payable (`withdrawMultiple`) as a part of https://github.com/sablier-labs/v2-core/pull/1087 (cc @andreivladbrg).

**Comment by andreivladbrg** [comment]
I was trying to implement this and am facing some issues. I’m afraid we won’t be able to achieve this via batch.

If we declare `batch` as `payable` and actually send a msg.value greater than 0, all functions within the `calls` array would also need to be declared as `payable`; otherwise, it would revert. Also, if we declare the `batch` function as payable (and all the other functions within calls are also `payable`), the fee paid by the caller would be `msg.value * length of the array`, which we don’t want.

This leads to the conclusion that we can’t declare it as `payable`, and we can’t use the `withdraw` function within the `batch` function.

**Comment by smol-ninja** [comment]
In the for loop inside `batch`, we can compare the selectors and if it matches with `withdraw` and `withdraw` related functions, then only we would forward `msg.value` to the delegate call.

What do you think of this?

**Comment by smol-ninja** [comment]
`delegatecall` forwards `msg.value`. [See here](https://medium.com/@olatunjimayowa0396/problem-with-payable-functions-using-delegatecall-inside-a-loop-c4f928314444) without specifying `value` parameters as long as the `batch` is `payable`.

**Comment by andreivladbrg** [comment]
we can't do this: `address(this).delegatecall{ value: msg.value }(calls[i]);`

**Comment by razgraf** [comment]
Curious, why does Uniswap's [multicall](https://github.com/Uniswap/v3-periphery/blob/main/contracts/base/Multicall.sol) work? What's different in their implementation?

**Comment by andreivladbrg** [comment]
> Curious, why does Uniswap's [multicall](https://github.com/Uniswap/v3-periphery/blob/main/contracts/base/Multicall.sol) work? What's different in their implementation?

they have declared all the functions where `Multicall` is inherited as `payable`, that's what we decided on the call as well

e.g.

https://github.com/Uniswap/v3-periphery/blob/0682387198a24c7cd63566a2c58398533860a5d1/contracts/SwapRouter.sol#L115-L117

https://github.com/Uniswap/v3-periphery/blob/0682387198a24c7cd63566a2c58398533860a5d1/contracts/SwapRouter.sol#L132-L134

https://github.com/Uniswap/v3-periphery/blob/0682387198a24c7cd63566a2c58398533860a5d1/contracts/SwapRouter.sol#L203-L205

https://github.com/Uniswap/v3-periphery/blob/0682387198a24c7cd63566a2c58398533860a5d1/contracts/SwapRouter.sol#L224-L226

etc..
