### ISSUE TITLE
Investigate why these remappings appear on the Etherscan verification reports

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#585]
During a recent [deployment](https://github.com/sablier-labs/v2-core/actions/runs/5422199478), I noticed that the "Settings" section on Etherscan reports a lot of remappings that have nothing to do with V2 Core:

<img width="618" alt="Screenshot 2023-08-23 at 10 29 57 AM" src="https://github.com/sablier-labs/v2-core/assets/8782666/5c5323da-b155-4ef7-980a-6070198c9cde">

This is strange because some of those remappings reference dependencies that are not longer used by V2 Core (e.g. `@prb/contracts`), and others whichthat have never been part of V2 Core (e.g. `@prb/proxy`).

Potential explanations:

1. Etherscan caching bug
2. Forge caching bug (Forge's state is somehow persistent across different workflow runs, including across different repos)

**Comment by andreivladbrg** [comment]
Since we are no longer using git submodules, we don't face this issue anymore. See the [LockupLinear](https://etherscan.io/address/0xAFb979d9afAd1aD27C5eFf4E27226E3AB9e5dCC9#code) contract

<img width="876" alt="image" src="https://github.com/sablier-labs/v2-core/assets/99738872/cb83a5cd-0d1e-457b-b217-f5dae4062704">

The only imports that appear are actually our configurations.
Should we close this? @PaulRBerg

**Comment by PaulRBerg** [comment]
Yep, let's close this.

It's also possible that they fixed this bug in Forge in the meantime. But the issue is fixed so either way, it doesn't matter.
