### ISSUE TITLE
Run fork tests on multiple chains

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#599]
The fork tests are currently run against a single chain.

Ref: https://github.com/foundry-rs/book/issues/872

**Comment by andreivladbrg** [comment]
I was thinking to address this issue. Since forge does not provide helpers I am thinking to apply this methodology:
- add a new foundry profile (fork multi chain - or any other name)
- this profile is going to be used only in `ci-fork`
- implement a util function to check this profile, similar to [isTestOptimizedProfile](https://github.com/sablier-labs/v2-core/blob/0a75661bc77f087620567265e1c7f973b1c504a8/test/utils/Utils.sol#L58-L61)
-  if the profile is specified run the fork tests against all [endpoints](https://github.com/sablier-labs/v2-core/blob/0a75661bc77f087620567265e1c7f973b1c504a8/foundry.toml#L93-L102) in `foundry.toml`, if any other profile is used, run only on mainnet
- implement a modifier to select all forks and run the same tests for all them
- introduce new datatypes for all information needed 

I am currently working on this locally, and it's going well. I will add the branch here once I push any commit.

Readind the code will also make it easier to understand my methodology from above.

@PaulRBerg tagging you to get notification

**Comment by andreivladbrg** [comment]
I have to admit, this is taking much longer than expected. One factor that influences the speed of the process is that it takes forever to run fork tests against multiple assets and chains.

I have successfully implemented this on [this branch](https://github.com/sablier-labs/v2-core/tree/test/fork-multichains), but only for Linear.

**Comment by PaulRBerg** [comment]
I agree with Shub, it's overkill to run cross-chain forks tests.

We're not a bridge so we are not interested in cross-chain communication. The Sablier protocol is siloed.

> after all they all are EVMs

There are some important differences in opcode pricing and gas calculations, but we at Sablier have the privilege of being able to ignore them.

**Comment by PaulRBerg** [comment]
Closing. Thank you for your efforts thus far @andreivladbrg.
