### ISSUE TITLE
Deploy to Sepolia?

### ISSUE THREAD

**Issue by waynehoover** [sablier-labs/v2-core#645]
I don't see any sepolia deployment addresses in [the docs](https://docs.sablier.com/contracts/v2/deployments). Do you plan to deploy to Sepolia? Goreli has gotten expensive, and its EOL is the end of this year.

**Comment by allwin199** [comment]
@PaulRBerg I would like to help with this.

**Comment by PaulRBerg** [comment]
Thanks kindly for your interest @allwin199 but unfortunately deployments require access to special deployer accounts, which are currently shared with our internal team only.

Besides that, deployments are also tricky to get right because they are irreversible. It is the kind of task that requires a pair programming effort.

**Comment by andreivladbrg** [comment]
Deployed all contracts on Sepolia: https://docs.sablier.com/contracts/v2/deployments#sepolia
