### ISSUE TITLE
Document the GitHub secrets required to make the CI work in PRs

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#715]
We should update the [`CONTRIBUTING`](https://github.com/sablier-labs/v2-core/blob/main/CONTRIBUTING.md) guide to explain what GitHub secrets contributors need to have set in order to make the CI pass in their forks.

Ref https://github.com/sablier-labs/v2-core/pull/714#issuecomment-1776954027

**Comment by smol-ninja** [comment]
Moving the discussion here:

The fork tests fails on a PR requested by an external contributor despite them passing in the local repo because secrets are not passed from the source branch to the workflows during a PR raised by an external contributor.

Ref: https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository

There is a solution: by using `pull_request_target` instead of `pull_request` event in GitHub Actions, the workflow will operate within the context of the contributor's forked repository secrets each time they open a new pull request.

Ref:
- https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks
- https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

Risks involved:
We just have to be extra careful when using `pull_request_target` as mentioned in this [Github blog](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/#:%7E:text=of%20the%20PR.-,Having%20said%20that,-%2C%20mixing%20pull_request_target%20with).

Should we look into `pull_request_target` event instead of `pull_request` in GitHub Actions?
