### ISSUE TITLE
Use "replace" function from Forge Std

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#843]
Since [v1.8.0](https://github.com/foundry-rs/forge-std/releases/tag/v1.8.0), Forge Std offers a `replace` cheatcode now:

https://github.com/foundry-rs/forge-std/blob/b6a506db2262cad5ff982a87789ee6d1558ec861/src/Vm.sol#L745-L749

It would be nice to be able to get rid of Solady - I know we're also using `Base64`, but maybe for that, OpenZeppelin has something now.

Related: https://github.com/sablier-labs/v2-core/issues/842

**Comment by PaulRBerg** [comment]
Ok, I still think it would be good to use Forge Std for `replace`.

**Comment by smol-ninja** [comment]
I've implemented this in https://github.com/sablier-labs/v2-core/pull/865. However, we will continue to rely on `solady` due to the following 3 functions:

1. `Base64.decode` - https://github.com/OpenZeppelin/openzeppelin-contracts/issues/4287 continues to remain open.
2. [string.indexOf(search)](https://github.com/Vectorized/solady/blob/b61da94a2d275471eec03b584d70ff31881ecfae/src/utils/LibString.sol#L554) - `forge-std` doesn't provide it yet.
3. [toHexStringNoPrefix(address)](https://github.com/Vectorized/solady/blob/b61da94a2d275471eec03b584d70ff31881ecfae/src/utils/LibString.sol#L288) - `forge-std` doesn't provide it yet but it has [a set of string manipulation functions](https://github.com/foundry-rs/forge-std/blob/bb4ceea94d6f10eeb5b41dc2391c6c8bf8e734ef/src/Vm.sol#L751C1-L758C93) that we may be able use to implement it ourselves.
