### ISSUE TITLE
Write backward compatibility tests for NFTDescriptor

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#881]
As discussed [here](https://github.com/sablier-labs/v2-core/discussions/877), we will deploy a new NFTDescriptor contract for V2.2.

We will then use our admin account and call `setNFTDescriptor` on all V2.0 and V2.1 deployments.

It would be helpful to write a few fork tests to prove that this is a safe operation.

**Comment by smol-ninja** [comment]
While working on this, I came to realize the new NFTDescriptor is not compatible with v2.0 but only with v2.1. This is due to the fact the new NFTDescriptor includes `isTransferable` in the svg description.

https://github.com/sablier-labs/v2-core/blob/76e29fee33befaeb54a82473c28cf182e6f8855d/src/SablierV2NFTDescriptor.sol#L96

v2.0 doesn't have `isTransferable`.

**Comment by PaulRBerg** [comment]
Houston, we have a problem. Is the solution to keep using the previous NFT descriptor for V2.0?

**Comment by smol-ninja** [comment]
> Houston, we have a problem. Is the solution to keep using the previous NFT descriptor for V2.0?

Yes! Or remove isTransferable from the NFT description but the [reason behind](https://github.com/sablier-labs/v2-core/issues/818) adding it is strong enough to keep it.

Additionally, we can use a low-level call to fetch isTransferable so in the case of V2.0, it would be just blank in the description. But wouldn't it confuse users?

**Comment by smol-ninja** [comment]
@PaulRBerg any comment on this?

**Comment by PaulRBerg** [comment]
> we can use a low-level call to fetch

This is da wei!

> it would be just blank in the description

It doesn't have to be blank. All V2.0 streams are transferable, so we can say that.
