### ISSUE TITLE
Refactor memory structs to have parameters in an alphabetical order

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/v2-core#888]
As discussed in https://github.com/sablier-labs/v2-periphery/discussions/313#discussioncomment-9060175, the goal is to refactor memory structs to have parameters in alphabetical order throughout the codebase.

**Comment by andreivladbrg** [comment]
I don't agree with this, I think this comment left by you @PaulRBerg is still relevant here: https://github.com/sablier-labs/v2-core/pull/784#issuecomment-1888921189

I consider the current version better, especially because:
"The reason for this is that it would (ironically) create more consistency among our create function calls - across the production code in src, the test code in test, and our [examples](https://github.com/sablier-labs/examples)"

Also tagging @razgraf as I remember that he mentioned that constantly renaming the order of the parameters in structs would increase the complexity of the app, since we need to maintain the backwards compatibility.

**Comment by razgraf** [comment]
I'm against re-ordering as well. The advantage of a slightly cleaner/non-opinionated struct here is too small to make the time spent refactoring our utilities worth it.

See this [backwards compatibility](https://github.com/sablier-labs/v2-subgraphs/blob/9b8ed4b136af01ddffb1545d1f056399bd7b65aa/apps/protocol/src/mappings/gateway.ts#L78-L111) code (nightmare) we have to write in order to maintain all versions of the protocol inside the subgraph. This extends to indexers, app etc.

As long as (1) there is no functional advantage (optimization, heavy gas reduction, security or logic) or (2) impressive cognitive load reduction / confusion reduction as far as DX goes, I please urge you to re-consider this type of refactors. I myself find it hard to keep track of these re-namings and re-orderings, cannot imagine what an external integrator has to go through.

**Comment by PaulRBerg** [comment]
@andreivladbrg and @razgraf, I've reopened https://github.com/sablier-labs/v2-periphery/discussions/313, could you please delete and move your comments there?
