### ISSUE TITLE
Fix fork tests for NFT descriptor

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#893]
As pointed out [here](https://github.com/sablier-labs/v2-core/pull/889/files#r1560494554), the following tests are incorrect:

- [`testForkFuzz_TokenURI_LockupDynamic_V2_0`](https://github.com/sablier-labs/v2-core/blob/e57553507b3a388c4a7245e04f36bd1dc014cbc0/test/fork/NFTDescriptor.t.sol#L50)
- [`testForkFuzz_TokenURI_LockupLinear_V2_0`](https://github.com/sablier-labs/v2-core/blob/e57553507b3a388c4a7245e04f36bd1dc014cbc0/test/fork/NFTDescriptor.t.sol#L84C14-L84C53)

The `tokenURIBefore` should NOT equal the `tokenURIAfter` because the latest NFT descriptor contains the note about transferability, whereas the previous NFTDescriptor (part of the V2.1 release) used by V2.0 doesn't contain such a note.

What we have to do:

1. Explain why the current test passes.
2. Rewrite the test to check for an inequality instead of an equality.
3. Decode the URI and look for the note about transferability (checking if the string contains the substring we're interested in).

**Comment by PaulRBerg** [comment]
Any updates on this, @smol-ninja? It's likely that this will get flagged during the audit.

**Comment by smol-ninja** [comment]
The tests are passing because the fuzzed streams are transferrable (since most streams are transferrable, the probability of getting a stream with non-transferability is very low). 

If `isTransferable` is `true`, the `description` field of `uri` will be the "same" for v2.2, v2.1 and v2.0. 

- [v2.0 generateDescription](https://github.com/sablier-labs/v2-core/blob/412ec3d3998a766507de96afdb26c797d2ae491d/src/SablierV2NFTDescriptor.sol#L260C1-L279C6)
- [v2.1 generateDescription](https://github.com/sablier-labs/v2-core/blob/a4bf69cf7024006b9a324eef433f20b74597eaaf/src/SablierV2NFTDescriptor.sol#L260C1-L279C6)
- [v2.2 generateDescription](https://github.com/sablier-labs/v2-core/blob/6f0879891b046fc14d941b2a58804193b25dff38/src/SablierV2NFTDescriptor.sol#L274C1-L296C11)

The description of v2.2 SVG only differs from v2.0 and v2.1 when `isTransferable` is `false` and that's when the test would also fail.

However, I was thinking since the goal is to check the "compatibility" of the new `NFTDescriptor` with previous deployments, the only necessary check should be that the call to `tokenURI` doesn't revert. So we should only check that it passes without to need for equality/inequality at all (we are doing that separately in `tokenURI.t.sol`).

What do you think about this?

**Comment by PaulRBerg** [comment]
Great sleuthing! You're right.

> the only necessary check should be that the call to tokenURI doesn't revert

Yeah, that makes sense.

There's no `expectNotRevert` so we can resort to adding an explanatory comment above the final call that explains this rationale.

**Comment by smol-ninja** [comment]
We have `expectCall`. I did some tests and the test fails if the call reverts.

**Comment by PaulRBerg** [comment]
Awesome, let's go with `expectCall` then
