### ISSUE TITLE
Running the CI Deep workflow manually results in errors

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#965]
See the recent run: https://github.com/sablier-labs/v2-core/actions/runs/9807405025

<img width="500" alt="SCR-20240705-mdqy" src="https://github.com/sablier-labs/v2-core/assets/8782666/cd48180b-2eaa-4604-938d-4c6591408022">

**Comment by smol-ninja** [comment]
The error is due to the syntax `${{ inputs.invariantDepth || 100 }}`. It wasn't before so may be Github changed how they parse digits in OR conditions.

The easiest solution would be to remove the OR condition and just use `${{ inputs.invariantDepth }}`. Any problem with that? All the inputs are anyways defined in the workflow file.

**Comment by PaulRBerg** [comment]
We have to keep using the OR syntax because otherwise `inputs` would be undefined when run by the weekly cron job.

I can't find it now, but there was a StackOverflow thread where I found the recommendation to use that syntax.

**Comment by smol-ninja** [comment]
I see. In that case, I will look for solutions.

**Comment by smol-ninja** [comment]
Re-opening it. Seems like the run works fine on automatic dispatch and only fails on manual dispatch.

**Comment by smol-ninja** [comment]
Finally, found the solutions:
1. Core PR: https://github.com/sablier-labs/v2-core/pull/968
2. Periphery PR: https://github.com/sablier-labs/v2-periphery/pull/366

Successful runs:
- https://github.com/sablier-labs/v2-core/actions/runs/9828167040
- https://github.com/sablier-labs/v2-periphery/actions/runs/9828236839

**Comment by PaulRBerg** [comment]
Great sleuthing @smol-ninja!
