### ISSUE TITLE
Running the CI Deep template via cron job fails

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-core#970]
See the latest run: https://github.com/sablier-labs/v2-core/actions/runs/9924854793

<img width="400" alt="SCR-20240715-lscv" src="https://github.com/user-attachments/assets/2d21abd6-7089-4fe7-b147-40c145474805">

Related:

- https://github.com/sablier-labs/v2-core/issues/965
- https://github.com/sablier-labs/v2-core/pull/968

**Comment by smol-ninja** [comment]
Thanks for noticing. I will look into it. Do you receive the failed CI results on your email? Is there a way to forward them to tech@sablier.com so that I can also receive them?

**Comment by PaulRBerg** [comment]
You're welcome.

I'd prefer not to send these updates to the tech@sablier.com email address to avoid spamming the frontend team with Solidity CI failures.

I shared a [pro tip](https://sablier.slack.com/archives/C038V3XB8N9/p1706872943560689) on Slack about how to set up email notifications for failed CI runs.

**Comment by PaulRBerg** [comment]
Thanks @smol-ninja. We might also want to reach out via GitHub Support; we're paying customers after all.

**Comment by smol-ninja** [comment]
Good idea. I have created a ticket with them.

**Comment by smol-ninja** [comment]
https://github.com/sablier-labs/v2-core/commit/a34e5287bb77c3e20b8fb9d3ef349a4a80d990aa and https://github.com/sablier-labs/v2-periphery/commit/2d338a7ff6452b20a25e779f5a960f047a5d16af should fix it now. The possible issue was that `fromJSON` requires `if` and `else` condition inside it.

So instead of `fromJSON(inputs.integrationFuzzRuns) || 100000` it should have been `fromJSON(inputs.integrationFuzzRuns || '100000')`.

**Comment by PaulRBerg** [comment]
Great! Let's see if it works next Sunday.

**Comment by smol-ninja** [comment]
Working now:
1. https://github.com/sablier-labs/v2-periphery/actions/runs/10233004613
2. https://github.com/sablier-labs/v2-core/actions/runs/10232982824/job/28310893019
